when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error
#
#homepage:
#    path: /arbre
#    controller: App\Controller\DecController::index